# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deutsch(self):
    self.driver.get("https://70000tons.com/")
    self.driver.maximize_window()
    self.driver.find_element(By.LINK_TEXT, "English").click()
    self.driver.find_element(By.LINK_TEXT, "English").click()
    self.driver.find_element(By.CSS_SELECTOR, "#mega-menu-item-wpml-ls-18-de .wpml-ls-native").click()
    
    self.driver.find_element(By.CSS_SELECTOR, "#intro-message > h1").click()
    assert self.driver.find_element(By.XPATH, "//*[@id=\"intro-message\"]/h1").text == "DAS ORIGINAL, DIE WELTGRÖSSTE HEAVY-METAL-KREUZFAHRT"
  
