# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestFaqtravel():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_faqtravel(self):
        self.driver.get("https://70000tons.com/")
        self.driver.set_window_size(1722, 1034)
        self.driver.find_element(By.LINK_TEXT, "English").click()

        WebDriverWait(self.driver, timeout=10).until(lambda d: d.find_element(
            By.XPATH, "/html/body/div[1]/header/nav/div/ul/li[6]"))
        self.driver.find_element(
            By.XPATH, "/html/body/div[1]/header/nav/div/ul/li[6]").click()

        WebDriverWait(self.driver, timeout=10).until(lambda d: d.find_element(
            By.XPATH, "/html/body/div[1]/div/section/article/section/div[1]/div[2]/div/div[1]/a"))
        self.driver.find_element(
            By.XPATH, "/html/body/div[1]/div/section/article/section/div[1]/div[2]/div/div[1]/a").click()
        self.driver.find_element(
            By.CSS_SELECTOR, ".su-accordion:nth-child(4) .su-spoiler-icon").click()
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(
            By.LINK_TEXT, "US State Department website").click()
        self.vars["win9655"] = self.wait_for_window(2000)
        self.driver.switch_to.window(self.vars["win9655"])
        assert self.driver.current_url == "https://travel.state.gov/content/travel/en/us-visas/visa-information-resources/wizard.html"
