name: test01
on: push  
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
         chrome-version: stable
      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Install the necessary packages
        run: pip install requests webdriver-manager selenium pytest
      - name: Run the PytTest script
        run: pytest -rA
