name: test01
on: push
jobs:
  test01:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      #Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install the necessary packages
        run: pip install chromedriver requests webdriver-manager selenium pytest

      - name: Run the PytTest script
        run: pytest -rA
